# Generated by Django 3.1.4 on 2020-12-30 23:35

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=64, verbose_name='Title')),
                ('cover_image', models.ImageField(help_text='Project cover image', upload_to=api.models.project_cover, verbose_name='Cover Image')),
                ('short_description', models.CharField(blank=True, default='', help_text='Example: Renovations and upgrades', max_length=32, verbose_name='Short Description')),
                ('description', models.TextField(help_text='Overview of the project, written in markdown', verbose_name='Project Description')),
                ('details', models.TextField(help_text='Details about the project, including specifics', verbose_name='Project Details')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='project Image', help_text='A title for the image', max_length=32, verbose_name='Project Image Text')),
                ('image', models.ImageField(upload_to=api.models.project_image, verbose_name='Project Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
        ),
    ]
