# Generated by Django 3.1.4 on 2020-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='text',
            field=models.CharField(default='Project Image', help_text='A title for the image', max_length=32, verbose_name='Project Image Text'),
        ),
    ]
