# Generated by Django 3.1.4 on 2020-12-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_licenses_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licenses',
            new_name='License',
        ),
    ]
