# Generated by Django 3.1.4 on 2020-12-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201231_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(default='', help_text='Name of company', max_length=64, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(default='Solutions License', help_text='Title of license to be displayed', max_length=64, verbose_name='License Title'),
        ),
    ]
